# Generated by Django 6.0.7 on 2026-08-20 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userban',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userban',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='article',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='saves_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='views_count',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='text_color',
        ),
        migrations.AddField(
            model_name='article',
            name='saves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_size_px',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='userban',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userban',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='userban',
            name='reason',
            field=models.TextField(blank=True, default='Причина не указана'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userban',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ban_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='userban',
            name='banned_at',
        ),
        migrations.RemoveField(
            model_name='userban',
            name='duration_type',
        ),
        migrations.RemoveField(
            model_name='userban',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='userban',
            name='is_active',
        ),
    ]
